### ISSUE TITLE
no Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by zeddius1983** [robinovitch61/kl#1]
When simply running 'kl' I'm getting this:

```
Error - if this seems wrong, consider opening an issue                                       
https://github.com/robino61/kl/issues/new                                                    
                                                                                             
ctrl+c to quit                                                                               
                                                                                             
failed to create clientset for cluster ***: no Auth Provider found for name "oidc"
```

I'm running this on mac os x, installed with a homebrew.

**Comment by zeddius1983** [comment]
Hi, yes of course.

I use 
`tkgi get-kubeconfig`
to authenticate and fetch configuration if it matters.

OpenLens, ks9 works fine after this.

**Comment by robinovitch61** [comment]
I don't use "Tanzu Kubernetes Grid Integrated" so I can't repro locally.

Run with `KL_DEBUG=1` set. Look at the `kl.log` file generated in the same directory where you run `kl`. You should see lines like:
```
2024/09/27 17:34:30.911368 "kubeconfig paths: [/Users/leo/.kube/config]"
2024/09/27 17:34:30.911714 "using contexts [k3d-test]"
2024/09/27 17:34:30.911731 "using cluster 'k3d-test' namespace 'default'"
2024/09/27 17:34:30.912070 "using context k3d-test for cluster k3d-test"
```
Hopefully that helps you debug. If you figure out what your issue is, let me know the details - I can hopefully add logic to fix your edge case.

PRs also welcome if you figure out how to fix it yourself

**Comment by robinovitch61** [comment]
Going to close this as without being able to repro, I also can't fix. If you have info required to repro, feel free to reopen

**Comment by robinovitch61** [comment]
I think this may be fixed now if you want to give it another go @zeddius1983

**Comment by zeddius1983** [comment]
I can confirm it is working now. Thank you.
